config/routes.rb
Rails.application.routes.draw do
  root 'hospitals#index'
  resources :hospitals
  resources :personnels
  resources :cooperation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :hospital
  belongs_to :personnel

  validates :hospital_id,
            uniqueness: { scope: :personnel_id }
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :collaborators, dependent: :destroy
  has_many :personnels, through: :collaborators

  validates :number,
            presence: true,
            uniqueness: true
end

app/models/personnel.rb
class Personnel < ApplicationRecord
  has_many :collaborators, dependent: :destroy
  has_many :hospitals, through: :collaborators

  validates :surname,
            presence: true,
            length: { maximum: 30 }

  validates :year_of_birth,
            presence: true,
            numericality: { only_integer: true,
                            greater_than_or_equal_to: 1900,
                            less_than_or_equal_to: ->(_brewery){ Date.current.year } }

  validates :position,
            presence: true

  enum position: %i(doctor nurse paramedic)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cooperation_controller.rb
class CooperationController < ApplicationController
  def create
    hire_personnel ? head(:ok) : head(:bad_request)
  end

  def destroy
    fire_personnel ? head(:ok) : head(:bad_request)
  end

  private

  def hire_personnel
    hospital&.personnels << personnel
  end

  def fire_personnel
    Collaborator.find(collabarator_params[:id]).destroy
  end

  def hospital
    Hospital.find(hospital_params[:hospital_id])
  end

  def personnel
    Personnel.find(personnel_params[:personnel_id])
  end

  def hospital_params
    params.permit(:hospital_id)
  end

  def personnel_params
    params.permit(:personnel_id)
  end

  def collabarator_params
    params.permit(:id)
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def show
    @hospital = Hospital.find(hospital_id)
    @avaible_personnels = Personnel.where.not(id: @hospital.personnels.select(:id))
  end

  def index
    @hospitals = Hospital.all
  end

  def create
    save_new_hospital ? head(:ok) : head(:bad_request)
  end

  def destroy
    delete_hospital ? head(:ok) : head(:bad_request)
  end

  private

  def save_new_hospital
    Hospital.new(hospital_params).save
  end

  def delete_hospital
    Hospital.find(hospital_id)&.destroy
  end

  def hospital_params
    params.permit(:number)
  end

  def hospital_id
    params[:id]
  end
end

app/controllers/personnels_controller.rb
class PersonnelsController < ApplicationController
  def show
    @personnel = Personnel.find(personnel_id)
  end

  def index
    @personnels = Personnel.all
  end

  def create
    save_new_personnel ? head(:ok) : head(:bad_request)
  end

  def destroy
    delete_personnel ? head(:ok) : head(:bad_request)
  end

  def update
    personnel&.update(personnel_update_params)
    redirect_to personnel_path(personnel_id)
  end

  private

  def personnel
    Personnel.find(personnel_id)
  end

  def save_new_personnel
    Personnel.new(personnel_params).save
  end

  def delete_personnel
    personnel&.destroy
  end

  def personnel_params
    params.permit(:surname, :year_of_birth, :position)
  end

  def personnel_update_params
    params.require(:personnel).permit(:surname, :year_of_birth, :position)
  end

  def personnel_id
    params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cooperation_helper.rb
module CooperationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
  def collabarator_id(hospital_id, personnel_id)
    Hospital.find(hospital_id).collaborators.where(personnel_id: personnel_id).first.id
  end
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/views/hospitals/_modal_new.html.slim
#new_hospital_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h4.modal-title = t('index.modal.header')
      .modal-body
        #modal_error.alert.alert-warning.hidden
          = t('index.modal.error')
        .form-group
          label for="modal_hospital_number"  = t('index.modal.lable')
          input#modal_hospital_number.form-control placeholder=("#{t('index.modal.input_placeholder')}") type="number" 




      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  = t('index.modal.bt_close')
        button.btn.btn-primary type="button" id="submit_modal"  = t('index.modal.bt_save')

app/views/hospitals/_personnel_table_content.html.slim
- workers.each_with_index do |personnel, index|
  tr id="#{personnel.id}"
    td
      = index + 1
    td 
      = link_to personnel.surname, personnel_path(personnel.id)
    td 
      = personnel.year_of_birth
    td 
      = personnel.position
    - if hired_personnel
      td 
        =link_to 'Fire', '#', id: 'fire_personnel', colloborator_id: collabarator_id(@hospital.id ,personnel.id)
    - else
      td
        =link_to 'Hire', '#', id: 'hire_personnel', personnel_id: personnel.id

app/views/hospitals/_table_content.html.slim
- @hospitals.each_with_index do |hospital, index|
  tr id="#{hospital.id}"
    td
      = index + 1
    td 
      = link_to hospital.number, hospital_path(hospital.id)
    td 
      =link_to 'Delete', '#', id: 'delete_hospital', hostital_id: hospital.id

app/views/hospitals/index.html.slim
h3 = t('index.header')
.col-md-4.col-md-offset-4
  table#hospitals_table.table.table-striped
    tr
      th = t('index.hospitals_table_header.index_number')
      th = t('index.hospitals_table_header.number')
      th =t('index.hospitals_table_header.delete_link')  
    = render partial: 'table_content'
  .create_new
    button.btn.btn-primary data-target="#new_hospital_modal" data-toggle="modal"  = t('index.create_new_bt')
= render partial: 'modal_new'

app/views/hospitals/show.html.slim
h3 id="#{@hospital.id}" = t('show.header', current_number: @hospital.number)
.col-md-6.col-md-offset-3
  - if @hospital.personnels.exists?
    h4 = t('show.hired_table_header')
    table#personnel_table.table.table-striped
      tr
        th = t('show.table.index_number')
        th = t('show.table.surname')
        th = t('show.table.year_of_birth')
        th = t('show.table.position')
        th =t('ishow.table.delete_link')  
      = render partial: 'personnel_table_content', locals: { workers: @hospital.personnels, hired_personnel: true }

.col-md-6.col-md-offset-3
  h4 = t('show.available_table_header')
  table#personnel_table.table.table-striped
    tr
      th = t('show.table.index_number')
      th = t('show.table.surname')
      th = t('show.table.year_of_birth')
      th = t('show.table.position')
      th =t('ishow.table.delete_link')  
    = render partial: 'personnel_table_content', locals: { workers: @avaible_personnels, hired_personnel: false }

app/views/layouts/_page_header_links.html.slim
.container
  .navbar-header
    button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href="#"  Test project
  .collapse.navbar-collapse
    ul.nav.navbar-nav
      li class="#{'active' if params[:controller] == 'hospitals' }"
        a href="#{root_path}"  = t('links.hospital')
      li class="#{'active' if params[:controller] == 'personnels'}"
        a href="#{personnels_path}"  = t('links.personnel')

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    meta content="" name="description" /
    meta content="" name="Andrii Horodnytskyi" /
    title IgiMEDTest
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .navbar.navbar-inverse.navbar-fixed-top role="navigation" 
      = render partial: 'layouts/page_header_links'
    .container.main_content
      = yield

app/views/personnels/_employers_table_content.html.slim
- @personnel.hospitals.each_with_index do |hospital, index|
  tr id="#{hospital.id}"
    td
      = index + 1
    td 
      = link_to hospital.number, hospital_path(hospital.id)
    

app/views/personnels/_modal_new.html.slim
#new_personnel_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h4.modal-title = t('index.modal.header')
      .modal-body
        #modal_error_year.alert.alert-warning.hidden
          = t('index.modal.error_invalid_year')
        #modal_error_surname.alert.alert-warning.hidden
          = t('index.modal.error_invalid_surname')

        .form-group
          label for="modal_personnel_surname"  = t('index.modal.lable_surname')
          input#modal_personnel_surname.form-control placeholder=("#{t('index.modal.input_placeholder_surname')}") type="text" size="30" 
        .form-group
          label for="modal_personnel_year_of_birth"  = t('index.modal.lable_year_of_birth')
          input#modal_personnel_year_of_birth.form-control placeholder=("#{t('index.modal.input_placeholder_year_of_birth')}") type="number" 

        .form-group
          label for="modal_personnel_position"  = t('index.modal.lable_position')
          select#modal_personnel_position.form-control
            option doctor
            option nurse
            option paramedic

      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  = t('index.modal.bt_close')
        button.btn.btn-primary type="button" id="submit_modal_personnel"  = t('index.modal.bt_save')

app/views/personnels/_table_content.html.slim
- @personnels.each_with_index do |personnel, index|
  tr id="#{personnel.id}"
    td
      = index + 1
    td 
      = link_to personnel.surname, personnel_path(personnel.id)
    td 
      = personnel.year_of_birth
    td 
      = personnel.position
    td 
      =link_to 'Delete', '#', id: 'delete_personnel', personnel_id: personnel.id

app/views/personnels/index.html.slim
h3 = t('index.header')
.col-md-6.col-md-offset-3
  table#personnel_table.table.table-striped
    tr
      th = t('index.personnels_table_header.index_number')
      th = t('index.personnels_table_header.surname')
      th = t('index.personnels_table_header.year_of_birth')
      th = t('index.personnels_table_header.position')
      th =t('index.personnels_table_header.delete_link')  
    = render partial: 'table_content'
  .create_new
    button.btn.btn-primary data-target="#new_personnel_modal" data-toggle="modal"  = t('index.create_new_bt')
= render partial: 'modal_new'

app/views/personnels/show.html.slim
h3 = t('show.header', user: @personnel.surname)
.col-md-6.col-md-offset-3
  h4 =t('show.form.header')
  br
  = form_for @personnel do |f|
    .form-group
      = f.label :surname, t('show.form.lable_surname')
      br
      = f.text_field :surname
    .form-group
      = f.label :year_of_birth, t('show.form.year_of_birth')
      br
      = f.text_field :year_of_birth

    .form-group
      = f.label :position, t('show.form.position')
      br
      = f.select :position, Personnel.positions.keys, {}
    .form-group
      = f.submit class: 'btn btn-default'

.col-md-6.col-md-offset-3
  h4 =t('show.employers_table.header')
  - if @personnel.hospitals.exists?
    table#employers_table.table.table-striped
      tr
        th = t('show.employers_table.index_number')
        th = t('show.employers_table.number') 
      = render partial: 'employers_table_content'
  - else 
    p
      = t('show.employers_table.not_hired') 